### ISSUE TITLE
备份时，建议使用：pdo的quote

### ISSUE THREAD

**Issue by hulang** [lotofbadcode/phpextend#2]
一直用你写的，但是字段中有特殊字符，就备份出错了。
这个我改了下。。

    private function _singleinsertrecord($tablename, $limit)
    {
        $sql = 'select * from `' . $tablename . '` limit ' . $limit . ',' . $this->_totallimit;
        $res = $this->_pdo->query($sql);
        $data = $res->fetchAll(PDO::FETCH_NUM);
        //
        $sql_list = [];
        // 写入表名注释
        $sql_list[] = "-- ----------------------------";
        $sql_list[] = "-- Records of {$tablename}";
        $sql_list[] = "-- ----------------------------";
        //
        if (!empty($data)) {
            foreach ($data as $k => $v) {
                $sql = "INSERT INTO `{$tablename}` VALUES(";
                $fields = [];
                //
                foreach ($v as $field) {
                    if (null !== $field) {
                        // 主要是这行
                        $fields[] = $this->_pdo->quote($field);
                    } else {
                        $fields[] = ' null';
                    }
                }
                $sql .= implode(',', $fields);
                $sql .= ");";
                //
                $sql_list[] = $sql;
            }
        }
        $insertsql = implode(PHP_EOL, $sql_list) . PHP_EOL;
        $this->_checkfilesize();
        file_put_contents($this->_backdir . '/' . $this->getfilename(), file_get_contents($this->_backdir . '/' . $this->getfilename()) . $insertsql);
        $this->_nowtableexeccount += $this->_totallimit;
        $this->_nowtableexeccount = $this->_nowtableexeccount >= $this->_nowtabletotal ? $this->_nowtabletotal : $this->_nowtableexeccount;
    }

**Comment by hulang** [comment]
我这个是老版本2017版本，最近才看到作者更新了。。还是没有使用：
pdo的quote

**Comment by lotofbadcode** [comment]
不好意思一直忙  才看到 有空一定改了

**Comment by hulang** [comment]
@lotofbadcode 好的，，https://github.com/lotofbadcode/phpextenddemo   是否支持最新版本额。。作者也一起测试下哦

**Comment by lotofbadcode** [comment]
最新版本还在调整 最新版加入了 建库建表的功能

**Comment by hulang** [comment]
@lotofbadcode 感谢作者写出这么好用的插件
备份时setbackdir指定的文件夹，能否系统内再创建一个以：年-月-日-时-分，即：Y-m-d-H-i
如：指定文件夹/2019-11-07-20-57/
主要是我php太菜，指定文件夹后，向以：Y-m-d-H-i创建，但是session貌似失效了。。。
作者老大，能否系统内加上，我看作者老大系统内用session弄的

**Comment by lotofbadcode** [comment]
这个问题 新版本已经考虑文件夹以时分秒的存储方式，你的失效问题应该是采用了AJAX 备份的方式 这个方式确实会出现session丢失的问题  新版本中为了兼容前后端分离 已弃用session的方式 ，最近应该会出新版本

**Comment by hulang** [comment]
@lotofbadcode 感谢作者老大额，哈哈，可以以：文件夹以时分秒的存储方式
太好了。

**Comment by hulang** [comment]
@lotofbadcode 发布下版本，我composer安装下额

**Comment by lotofbadcode** [comment]
不好意思，这两天会发布新版本

**Comment by hulang** [comment]
@lotofbadcode 出现个奇怪的问题，本地测试OK，服务器上，一直卡在一个地方，返回结果：
{"code":2,"message":"file_get_contents(1.txt): failed to open stream: No such file or directory"}
方便加QQ指点下么？

**Comment by lotofbadcode** [comment]
301行删掉 我测试的忘记删了

**Comment by hulang** [comment]
@lotofbadcode 推送下版本啊，不然只能手动更新了。

**Comment by lotofbadcode** [comment]
本地删除重新安装就好了

**Comment by lotofbadcode** [comment]
为了更好的升级和维护，减少使用者的代码冗余，决定将多个扩展分开开发和单独安装，该代码不再维护，但是永远可以使用，已将该项目下的两个插件分别做两个项目维护，阅读文档 请点击 https://www.kancloud.cn/lotofbadcode/php_spirit/content

**Comment by hulang** [comment]
@lotofbadcode 好的
