### ISSUE TITLE
2.0不使用ajax备份的说明有问题

### ISSUE THREAD

**Issue by lazzzy18** [lotofbadcode/phpextend#4]
https://github.com/lotofbadcode/phpextend/blame/master/READMEV2.0.md#L22
应修改为
$backup = BackupFactory::instance('mysql', '127.0.0.1:3306', 'qjfsonar', 'root', 'root');

**Comment by lotofbadcode** [comment]
已修改，为了更好的升级和维护，减少使用者的代码冗余，决定将多个扩展分开开发和单独安装，该代码不再维护，但是永远可以使用，已将该项目下的两个插件分别做两个项目维护，阅读文档 请点击 https://www.kancloud.cn/lotofbadcode/php_spirit/content
