### ISSUE TITLE
2.0 ajax备份只能备份第一个数据表

### ISSUE THREAD

**Issue by lazzzy18** [lotofbadcode/phpextend#5]
是我使用出了问题吗？
不使用ajax方法备份可以备份所有的数据。
使用ajax备份的时候，只能备份数据库的第一个数据表。

**Comment by lazzzy18** [comment]
感觉是您的2.0说明文档有问题。不使用ajax备份的示例代码中有do...while循环。使用ajax方式备份的示例代码中没有do...while循环。

**Comment by lazzzy18** [comment]
另外也测试了phpextenddemo中的示例，同样只能备份第一个数据表。

**Comment by lotofbadcode** [comment]
demo写的冲忙 有空改下 最近事太多了

**Comment by lazzzy18** [comment]
好的，谢谢！

**Comment by lotofbadcode** [comment]
为了更好的升级和维护，减少使用者的代码冗余，决定将多个扩展分开开发和单独安装，该代码不再维护，但是永远可以使用，已将该项目下的两个插件分别做两个项目维护，阅读文档 请点击 https://www.kancloud.cn/lotofbadcode/php_spirit/content

**Comment by lazzzy18** [comment]
您好，我阅读修改后的代码发现，您给出的 ajaxbackup 示例没有使用do...while循环。阅读ajaxbackup源码发现，如果按照给出的示例来用的话，应该还是只能备份第一个数据表。

**Comment by lotofbadcode** [comment]
加QQ群：601032045 或者看最新的手册
